name: shuukimori
description: Custom Kinoite build aimed to add several QoLs (and non-QoLs too!)

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
    - from-file: commons/files.yml
    - from-file: commons/rpm-ostree.yml
    - from-file: commons/default-flatpaks.yml

- type: signing
